// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicTopSection,
  DefaultTopSectionProps
} from "./plasmic/dogev_3/PlasmicTopSection";
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import { useFetch } from "../hooks/useFetch";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface TopSectionProps extends Omit<DefaultTopSectionProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultTopSectionProps altogether and have
// total control over the props for your component.
interface TopSectionProps extends DefaultTopSectionProps {}

function TopSection_(props: TopSectionProps, ref: HTMLElementRefOf<"div">) {
  // Use PlasmicTopSection to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicTopSection are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all TopSectionProps here, but feel free
  // to do whatever works for you.
  const json = useFetch<{
    currentStageId: string,
    startTimestamp: string,
    tokenId: string,
    tokenId2: string,
    upperPrice: number,
    lowerPrice: number,
    currentPrice: number,
  }>("https://gist.githubusercontent.com/9ab78f5225ff4a4cae8ba303/db6b693480341decf9648d9f3c496da2/raw/sample.json");
  const children = <div>
    {`upper price: $${json?.upperPrice}
    lower price: $${json?.lowerPrice}
    DOGEV3: $${json?.currentPrice}
    Current Stage: ${json?.currentStageId}
    Need to ${(json?.upperPrice/json?.currentPrice).toFixed((2))}x from current price to rev up to Stage ${json?.currentStageId}`}
  </div>;
  return <PlasmicTopSection root={{ ref }} {...props}>{children}</PlasmicTopSection>;
}

const TopSection = React.forwardRef(TopSection_);
export default TopSection;
