// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicTopSection4,
  DefaultTopSection4Props
} from "./plasmic/dogev_3/PlasmicTopSection4";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface TopSection4Props extends Omit<DefaultTopSection4Props, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultTopSection4Props altogether and have
// total control over the props for your component.
interface TopSection4Props extends DefaultTopSection4Props {}

function TopSection4_(props: TopSection4Props, ref: HTMLElementRefOf<"div">) {
  // Use PlasmicTopSection4 to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicTopSection4 are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all TopSection4Props here, but feel free
  // to do whatever works for you.

  return <PlasmicTopSection4 root={{ ref }} {...props} />;
}

const TopSection4 = React.forwardRef(TopSection4_);
export default TopSection4;
