// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uhjxjVT6QbAZLostZzQbnY
// Component: l3hFJlm9M5
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import LinkButton from "../../LinkButton"; // plasmic-import: MbX3pXP-Npo9k/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_dogev_3.module.css"; // plasmic-import: uhjxjVT6QbAZLostZzQbnY/projectcss
import * as sty from "./PlasmicWhitepaper.module.css"; // plasmic-import: l3hFJlm9M5/css

export type PlasmicWhitepaper__VariantMembers = {};

export type PlasmicWhitepaper__VariantsArgs = {};
type VariantPropType = keyof PlasmicWhitepaper__VariantsArgs;
export const PlasmicWhitepaper__VariantProps = new Array<VariantPropType>();

export type PlasmicWhitepaper__ArgsType = {};
type ArgPropType = keyof PlasmicWhitepaper__ArgsType;
export const PlasmicWhitepaper__ArgProps = new Array<ArgPropType>();

export type PlasmicWhitepaper__OverridesType = {
  root?: p.Flex<"div">;
  linkButton?: p.Flex<typeof LinkButton>;
};

export interface DefaultWhitepaperProps {
  dataFetches: PlasmicWhitepaper__Fetches;
}

function PlasmicWhitepaper__RenderFunc(props: {
  variants: PlasmicWhitepaper__VariantsArgs;
  args: PlasmicWhitepaper__ArgsType;
  overrides: PlasmicWhitepaper__OverridesType;
  dataFetches?: PlasmicWhitepaper__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <React.Fragment>
      <Head>
        <title key="title">{""}</title>
        <meta key="og:title" property="og:title" content={""} />
        <meta
          key="description"
          name="description"
          property="og:description"
          content={""}
        />
      </Head>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <div className={classNames(defaultcss.all, sty.box__b2YdJ)}>
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__xf0GN
              )}
            >
              {"Who reads that dog poop anymore these days."}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__t1EVb
              )}
            >
              {
                "Conserve paper and save the trees🌲, forests🌲🌲🌲 and puppies🐶🐶🐶\n"
              }
            </div>

            <LinkButton
              data-plasmic-name={"linkButton"}
              data-plasmic-override={overrides.linkButton}
              className={classNames("__wab_instance", sty.linkButton)}
              href={"/#buy" as const}
              text={
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box___9TWxs
                  )}
                >
                  {"Buy Now"}
                </div>
              }
              type={"solidBlack" as const}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "linkButton"],
  linkButton: ["linkButton"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  linkButton: typeof LinkButton;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicWhitepaper__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicWhitepaper__VariantsArgs;
    args?: PlasmicWhitepaper__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicWhitepaper__Fetches;
  } & Omit<PlasmicWhitepaper__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicWhitepaper__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicWhitepaper__ArgProps,
      internalVariantPropNames: PlasmicWhitepaper__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicWhitepaper__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicWhitepaper";
  } else {
    func.displayName = `PlasmicWhitepaper.${nodeName}`;
  }
  return func;
}

export const PlasmicWhitepaper = Object.assign(
  // Top-level PlasmicWhitepaper renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    linkButton: makeNodeComponent("linkButton"),

    // Metadata about props expected for PlasmicWhitepaper
    internalVariantProps: PlasmicWhitepaper__VariantProps,
    internalArgProps: PlasmicWhitepaper__ArgProps
  }
);

export default PlasmicWhitepaper;
/* prettier-ignore-end */
