// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uhjxjVT6QbAZLostZzQbnY
// Component: jhnS_v6HGz
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_dogev_3.module.css"; // plasmic-import: uhjxjVT6QbAZLostZzQbnY/projectcss
import * as sty from "./PlasmicMenuButton.module.css"; // plasmic-import: jhnS_v6HGz/css

import ClosesvgIcon from "./icons/PlasmicIcon__Closesvg"; // plasmic-import: xEgu2zZiEl/icon
import MenusvgIcon from "./icons/PlasmicIcon__Menusvg"; // plasmic-import: ZAYKxCR5Ty/icon

export type PlasmicMenuButton__VariantMembers = {
  toggled: "toggled";
};

export type PlasmicMenuButton__VariantsArgs = {
  setToggled?: (toggled: boolean) => void;
  toggled?: SingleBooleanChoiceArg<"toggled">;
};

type VariantPropType = keyof PlasmicMenuButton__VariantsArgs;
export const PlasmicMenuButton__VariantProps = new Array<VariantPropType>(
  "toggled"
);

export type PlasmicMenuButton__ArgsType = {};
type ArgPropType = keyof PlasmicMenuButton__ArgsType;
export const PlasmicMenuButton__ArgProps = new Array<ArgPropType>();

export type PlasmicMenuButton__OverridesType = {
  root?: p.Flex<"div">;
  box?: p.Flex<"div">;
  close?: p.Flex<"svg">;
  menu?: p.Flex<"svg">;
};

export interface DefaultMenuButtonProps {
  setToggled?: (toggled: boolean) => void;
  toggled?: SingleBooleanChoiceArg<"toggled">;
  className?: string;
}

function PlasmicMenuButton__RenderFunc(props: {
  variants: PlasmicMenuButton__VariantsArgs;
  args: PlasmicMenuButton__ArgsType;
  overrides: PlasmicMenuButton__OverridesType;
  dataFetches?: PlasmicMenuButton__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root, {
        [sty.root__toggled]: hasVariant(variants, "toggled", "toggled")
      })}
      onClick={() => variants.setToggled(!variants.toggled)}
    >
      <div
        data-plasmic-name={"box"}
        data-plasmic-override={overrides.box}
        className={classNames(defaultcss.all, sty.box, {
          [sty.box__toggled]: hasVariant(variants, "toggled", "toggled")
        })}
      >
        {(hasVariant(variants, "toggled", "toggled") ? true : false) ? (
          <ClosesvgIcon
            data-plasmic-name={"close"}
            data-plasmic-override={overrides.close}
            className={classNames(defaultcss.all, sty.close, {
              [sty.close__toggled]: hasVariant(variants, "toggled", "toggled")
            })}
            id={"" as const}
            role={"img"}
          />
        ) : null}

        <MenusvgIcon
          data-plasmic-name={"menu"}
          data-plasmic-override={overrides.menu}
          className={classNames(defaultcss.all, sty.menu, {
            [sty.menu__toggled]: hasVariant(variants, "toggled", "toggled")
          })}
          role={"img"}
        />
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "box", "close", "menu"],
  box: ["box", "close", "menu"],
  close: ["close"],
  menu: ["menu"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  box: "div";
  close: "svg";
  menu: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMenuButton__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMenuButton__VariantsArgs;
    args?: PlasmicMenuButton__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicMenuButton__Fetches;
  } & Omit<PlasmicMenuButton__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicMenuButton__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicMenuButton__ArgProps,
      internalVariantPropNames: PlasmicMenuButton__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicMenuButton__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMenuButton";
  } else {
    func.displayName = `PlasmicMenuButton.${nodeName}`;
  }
  return func;
}

export const PlasmicMenuButton = Object.assign(
  // Top-level PlasmicMenuButton renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    box: makeNodeComponent("box"),
    close: makeNodeComponent("close"),
    menu: makeNodeComponent("menu"),

    // Metadata about props expected for PlasmicMenuButton
    internalVariantProps: PlasmicMenuButton__VariantProps,
    internalArgProps: PlasmicMenuButton__ArgProps
  }
);

export default PlasmicMenuButton;
/* prettier-ignore-end */
