// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uhjxjVT6QbAZLostZzQbnY
// Component: 3mrC-Y_5Jo
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_dogev_3.module.css"; // plasmic-import: uhjxjVT6QbAZLostZzQbnY/projectcss
import * as sty from "./PlasmicWhitepaperModal.module.css"; // plasmic-import: 3mrC-Y_5Jo/css

export type PlasmicWhitepaperModal__VariantMembers = {};

export type PlasmicWhitepaperModal__VariantsArgs = {};
type VariantPropType = keyof PlasmicWhitepaperModal__VariantsArgs;
export const PlasmicWhitepaperModal__VariantProps =
  new Array<VariantPropType>();

export type PlasmicWhitepaperModal__ArgsType = {};
type ArgPropType = keyof PlasmicWhitepaperModal__ArgsType;
export const PlasmicWhitepaperModal__ArgProps = new Array<ArgPropType>();

export type PlasmicWhitepaperModal__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultWhitepaperModalProps {
  className?: string;
}

function PlasmicWhitepaperModal__RenderFunc(props: {
  variants: PlasmicWhitepaperModal__VariantsArgs;
  args: PlasmicWhitepaperModal__ArgsType;
  overrides: PlasmicWhitepaperModal__OverridesType;
  dataFetches?: PlasmicWhitepaperModal__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div className={classNames(defaultcss.all, sty.box__qXlDy)}>
        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.box__uiPg
          )}
        >
          {"Whitepaper"}
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicWhitepaperModal__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicWhitepaperModal__VariantsArgs;
    args?: PlasmicWhitepaperModal__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicWhitepaperModal__Fetches;
  } & Omit<PlasmicWhitepaperModal__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicWhitepaperModal__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicWhitepaperModal__ArgProps,
      internalVariantPropNames: PlasmicWhitepaperModal__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicWhitepaperModal__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicWhitepaperModal";
  } else {
    func.displayName = `PlasmicWhitepaperModal.${nodeName}`;
  }
  return func;
}

export const PlasmicWhitepaperModal = Object.assign(
  // Top-level PlasmicWhitepaperModal renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicWhitepaperModal
    internalVariantProps: PlasmicWhitepaperModal__VariantProps,
    internalArgProps: PlasmicWhitepaperModal__ArgProps
  }
);

export default PlasmicWhitepaperModal;
/* prettier-ignore-end */
