// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { ScreenVariantProvider } from "../components/plasmic/dogev_3/PlasmicGlobalVariant__Screen";
import { NameContext } from "../components/plasmic/dogev_3/PlasmicGlobalVariant__Name";
import { PlasmicWhitepaper } from "../components/plasmic/dogev_3/PlasmicWhitepaper";

function Whitepaper() {
  // Use PlasmicWhitepaper to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicWhitepaper are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, PlasmicWhitepaper is wrapped by your project's global
  // variant context providers. These wrappers may be moved to
  // Next.js Custom App component
  // (https://nextjs.org/docs/advanced-features/custom-app).
  return (
    <NameContext.Provider value={undefined}>
      <PlasmicWhitepaper />
    </NameContext.Provider>
  );
}

export default Whitepaper;
